# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scout_api', '0005_gap'),
    ]

    operations = [
        migrations.AddField(
            model_name='sighting',
            name='town',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
