# Generated by Django 6.0.3 on 2026-03-19 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scout_api', '0007_town_and_sighting_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='gap',
            name='stage',
            field=models.CharField(blank=True, choices=[('contacted', 'Contacted'), ('visit_booked', 'Visit booked'), ('now_stocking', 'Now stocking'), ('declined', 'Declined')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='gap',
            name='status',
            field=models.CharField(blank=True, choices=[('pursue', 'Pursue'), ('revisit', 'Revisit'), ('skip', 'Not pursuing')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='gap',
            name='town',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gaps', to='scout_api.town'),
        ),
    ]
